function tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)

fig=figure( ...
           'Name','Amplificator fundamental TECMOS cu Drena Comuna', ...
           'NumberTitle','off', ...
           'Color','#BFD7FF',...
           'Units','Normalized',...
           'Visible','on',...
           'Position',[0.1 0.1 0.8 0.8]);


%% Facem semnalul vi
T=1/f;   
t=0:T/100:3*T;  %3 e numarul perioadelor
vi=A*sin(2*pi*f*t);

%% Aflam celelalte lucruri din schema
%tot ce contine 1 in nume e ori jumate de calcul ori 1/x
%RG=RG*(10^6);
gm= sqrt(2*K*WL*I);
ro=VA/I; %sau rds
Av=(gm*RS)/(1+gm*RS);
Ri=RG*(10^6);  %rezistenta de intrare
gm1=1/gm;%pentru a face mai scurte calculele
Ro1=(RS*ro)/(RS+ro);
Ro=(Ro1*gm1)/(Ro1+gm1);
vo=Av*vi;
vgs=vi-vo;

%% facem interfata grafica

%Facem afisarea imaginii
if ImagSchema==1
    x=imread('Schemanormala.png');
    subplot(3,1,1);
    imshow(x,[]);
    title('Amplificator fundamental TECMOS cu Drena Comuna', 'FontSize', 10, 'Interpreter', 'None');
    butonIm1=uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized', ...
                'Position',[0.45 0.6 0.15 0.06], ...
                'String','Schema semnal mic', ...
                'Callback','close;ImagSchema=2;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice);');
else
    x=imread('Schemasemnalmic.png');
    subplot(3,1,1);
    imshow(x,[]);
    title(["Amplificator fundamental TECMOS cu Drena Comuna","Schema semnal mic"], 'FontSize', 10, 'Interpreter', 'None');
    butonIm2=uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized', ...
                'Position',[0.45 0.6 0.15 0.06], ...
                'String','Schema normala', ...
                'Callback','close;ImagSchema=1;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice);');
end

%% graficile
if grafice==1
    subplot(4,3,6);
    plot(vi);
    yticks(-A-2:A/5:A+2); %sa apara numere mai frecvent
    ylim([(-A-2) (A+2)])  %sa nu se termine semnalul sinusoidal in capat
    ylabel("vi [mV]");
    xlabel("frecventa [Hz]");
    subplot(4,3,9);
    plot(vo);
    yticks(-A-2:A/4:A+2);
    ylabel("vo [mv]");
    xlabel("frecventa [Hz]");
    subplot(4,3,12);
    plot(vgs);
    %yticks(-A-2:A/4:A+2);
    ylabel("vgs [mv]");
    xlabel("frecventa [Hz]");
    butonTab1=uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized', ...
                'Position',[0.45 0.12 0.15 0.06], ...
                'String','Un singur grafic', ...
                'Callback','close;grafice=2;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice);');
else
    subplot(3,3,6);
    plot(vi);
    hold on;
    plot(vo);
    hold on;
    plot(vgs);
    hold off;
    xlabel("frecventa [Hz]");
    ylabel("mV");
    legend('vi','vo','vgs');
    butonTab2=uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized', ...
                'Position',[0.45 0.12 0.15 0.06], ...
                'String','Trei grafice', ...
                'Callback','close;grafice=1;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice);');
end


%% butoanele text si edit

% grup de butoane pentru semnalul vi  

%amplitudine
SemnIntr=uibuttongroup('Visible','on',...
'BackgroundColor','#BFD7FF',...
'ForegroundColor','black',...
'Title','Semnal de intrare: ',...
'FontSize',8,...
'FontWeight','bold',...
'TitlePosition','centertop',...
'Position',[0.08 0.65 0.25 0.2]);

BA=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.70 0.12 0.20],...
'BackgroundColor','#BFD7FF',...
'String','A=',...
'Parent',SemnIntr);

BAe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.25 0.70 0.2 0.20],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',A,...
            'Callback','A=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',SemnIntr);
BA=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.45 0.70 0.50 0.20],...
'BackgroundColor','#BFD7FF',...
'String','[mv] Amplitudinea',...
'Parent',SemnIntr);

%frecventa
Bf=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.40 0.12 0.20],...
'BackgroundColor','#BFD7FF',...
'String','f=',...
'Parent',SemnIntr);
Bfe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.25 0.40 0.2 0.20],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',f,...
            'Callback','f=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',SemnIntr);
BAt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.45 0.40 0.50 0.20],...
'BackgroundColor','#BFD7FF',...
'String','[Hz] frecventa semnalului',...
'Parent',SemnIntr);

%grup de butoane pentru celelalte lucruri din tranzistor
Altele=uibuttongroup('Visible','on',...
'BackgroundColor','#BFD7FF',...
'ForegroundColor','black',...
'Title','Parametrii circuitului ',...
'FontSize',8,...
'FontWeight','bold',...
'TitlePosition','centertop',...
'Position',[0.08 0.10 0.25 0.5]);

BI=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.87 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','I=',...
'Parent',Altele);
BIe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.87 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',I,...
            'Callback','I=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
BIt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.50 0.87 0.20 0.08],...
'BackgroundColor','#BFD7FF',...
'String','[A]',...
'Parent',Altele);

BRG=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.77 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','RG=',...
'Parent',Altele);
BRGe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.77 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',RG,...
            'Callback','RG=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
BRGt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.50 0.77 0.40 0.08],...
'BackgroundColor','#BFD7FF',...
'String','[Mega Ohm]',...
'Parent',Altele);

BRS=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.67 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','RS=',...
'Parent',Altele);
BRSe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.67 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',RS,...
            'Callback','RS=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
BRSt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.50 0.67 0.40 0.08],...
'BackgroundColor','#BFD7FF',...
'String','[Kilo Ohm]',...
'Parent',Altele);

BK=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.57 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','K=',...
'Parent',Altele);
BKe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.57 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',K,...
            'Callback','K=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
BKt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.50 0.57 0.40 0.08],...
'BackgroundColor','#BFD7FF',...
'String','[A/V^2]',...
'Parent',Altele);

BWL=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.47 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','W/L=',...
'Parent',Altele);
BWLe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.47 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',WL,...
            'Callback','WL=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
% BWLt=uicontrol('Style','text',...
% 'Units','normalized',...
% 'Position',[0.50 0.57 0.40 0.08],...
% 'BackgroundColor',[0.75,0.75,0.85],...
% 'String','[A/V^2]',...
% 'Parent',Altele);

BVA=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.37 0.12 0.08],...
'BackgroundColor','#BFD7FF',...
'String','VA=',...
'Parent',Altele);
BVAe=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.20 0.37 0.3 0.08],...
            'BackgroundColor','w',...
            'ForegroundColor','black',...
            'String',VA,...
            'Callback','VA=str2num(get(gco,''string''));close;tranzistorDC(I,RG,RS,K,WL,VA,A,f,ImagSchema,grafice)',...
            'Parent',Altele);
BVAt=uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.50 0.37 0.40 0.08],...
'BackgroundColor','#BFD7FF',...
'String','[v]',...
'Parent',Altele);

%%Afisajul calculelor 

Afisaje=uibuttongroup('Visible','on',...
'BackgroundColor',[0.75,0.75,0.85],...
'ForegroundColor','black',...
'Title','Performantele etajului DC',...
'FontSize',8,...
'FontWeight','bold',...
'TitlePosition','centertop',...
'Position',[0.45 0.2 0.15 0.35]);
  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.85 0.80 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String','Amplificarea in tensiune:',...
'FontAngle','italic',...
'Parent',Afisaje);
  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.78 0.90 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String',"Av= "+ Av,...
'Parent',Afisaje);

  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.58 0.80 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String','Rezistenta de intrare:',...
'FontAngle','italic',...
'Parent',Afisaje);
  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.51 0.90 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String',"Ri= "+ Ri+" Ohm",...
'Parent',Afisaje);

  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.31 0.80 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String','Rezistenta de iesire:',...
'FontAngle','italic',...
'Parent',Afisaje);
  uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.05 0.24 0.90 0.08],...
'BackgroundColor',[0.75,0.75,0.85],...
'String',"Ro= "+ Ro+" Ohm",...
'Parent',Afisaje);


% am facut un buton pentru o iesire mai facila din aplicatie
B_iesire=uicontrol( ...
                   'Style','pushbutton', ...
                   'Units','normalized', ...
                   'Position',[0.89 0.02 0.10 0.06], ...
                   'String','Iesire', ...
                   'Callback','close;');